config/routes.rb
RubyApi::Application.routes.draw do
  root to: "top#index"

  resources :paragraphs, only: [:update]

  lang = /\w\w(-\w\w)?/
  ver = /\d.\d.\d/
  lib = /[a-z].*/

  get ":lang/:version/:library/:module/:::name" => "main#show_constant"       , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module/.:name"  => "main#show_class_method"   , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module/:name"   => "main#show_instance_method", :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module"         => "main#show_module"         , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library"                 => "main#show_library"        , :lang => lang, :version => ver, :library => lib

  get ":lang/:version/:module/:::name" => "main#show_constant"       , :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module/.:name"  => "main#show_class_method"   , :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module/:name"   => "main#show_instance_method", :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module"         => "main#show_module"         , :lang => lang, :version => ver, :library => "_builtin"

  get ":lang/:version" => "main#show_language_top", :lang => lang, :version => ver

  get ":lang" => redirect("/%{lang}/1.9.3"), :lang => lang

end

app/controllers/main_controller.rb
require 'rdoc_helper.rb'

class MainController < ApplicationController
  before_filter :set_language, :set_version, :prepare_menu
  layout :set_layout

  def show_language_top
    # render view
  end

  def show_library
    find_entry(params[:library]) do |entry|
      @entry = entry
      @document = find_document(@entry)
      #@methods = Entry.where(version_id: @version.id, "fullname LIKE ?", @entry.fullname + "%")
    end
  end

  def show_module
    find_entry("#{params[:library]};#{params[:module]}") do |entry|
      @entry = entry
      @document = find_document(@entry)
      @singleton_methods = @entry.singleton_methods
      @instance_methods = @entry.instance_methods
      @constants = @entry.constants
    end
  end

  def show_class_method
    find_entry("#{params[:library]};#{params[:module]}.#{params[:name]}") do |entry|
      @entry = entry
      @document = find_document(@entry)
    end

    render "show_method"
  end

  def show_instance_method
    find_entry("#{params[:library]};#{params[:module]}##{params[:name]}") do |entry|
      @entry = entry
      @document = find_document(@entry)
    end

    render "show_method"
  end

  def show_constant
    find_entry("#{params[:library]};#{params[:module]}::#{params[:name]}") do |entry|
      @entry = entry
      @document = find_document(@entry)
    end

    render "show_method"
  end

  private

  def pjax?
   request.headers['X-PJAX']
  end

  def set_layout
   if pjax? then false else "main" end
  end

  def set_language
    @language = Language.from_short_name(params[:lang])
  end

  def set_version
    @version = Version[params[:version]] || Version.latest
  end

  def prepare_menu
    #@modules = [[],[]]; @libraries = []; return
    unless pjax?
      @modules = Entry.builtin_modules(@version)
      @libraries = [] #Entry.libraries(@version)
    end
  end

  def find_entry(fullname)
    if entry = Entry.where(fullname: fullname, version_id: @version.id).first
      yield entry
    else
      not_found
    end
  end

  # May return nil
  def find_document(entry)
    load './lib/document_extractor.rb'
    #return RubyApi::DocumentExtractor.for(@language, @version).extract_document(entry)

    Document.where(entry_id: entry.id,
                   language_id: @language.id).first
  end
end

app/helpers/main_helper.rb
module MainHelper
  def render_tree(tree, &block)
    return if tree.empty?

    concat "<ul>".html_safe
    tree.each do |parent, children|
      if children.empty?
        concat "<li>".html_safe
        block.call(parent)
        concat "</li>".html_safe
      else
        concat "<li><a class='tree_button' href='#'>[-]</a>".html_safe
        concat "<span>".html_safe
        block.call(parent)
        concat "</span>".html_safe
        render_tree(children, &block)
        concat "</li>".html_safe
      end
    end
    concat "</ul>".html_safe
  end
end

app/views/main/_document.html.slim
- case
- when document.nil?
  div No doc available!

- when document.body
  // English
  == RubyApi::RDocHelper.html(document.body)

- else
  // Translation form
  = render partial: "paragraph", collection: document.paragraphs

app/views/main/_entry.html.slim
span.entry
  = link_to entry.belong_name, entry.path(@language, @version)

app/views/main/_paragraph.html.slim
// A Paragraph and its translation form

.paragraph
  .spinner

  .current_text
    div class=(paragraph.translated? ? "translated" : "not_translated")
      == paragraph.html

  pre.original_text.hidden
    = paragraph.original.body

  form.hidden
    textarea rows=10 cols=100
      = paragraph.text
    = button_tag "cancel", class: "cancel"
    = submit_tag "save", class: "update_paragraph", data: {url: paragraph_path(paragraph)}

app/views/main/show_language_top.html.slim
- case @language.short_name
- when "en"
  h1 Ruby Reference Manual

  p (under construction)
- when "ja"
  h1 Rubyリファレンスマニュアル

  p (準備中)
- when "eo"
  h1 Esperanto (Translation Test)

  p This is an example of how translation is supported.

app/views/main/show_library.html.slim
h1= @entry.name
= render partial: "document", object: @document

app/views/main/show_method.html.slim
h1= @entry.belong_name
= render partial: "document", object: @document

ul
  li= render partial: "entry", object: @entry.module

app/views/main/show_module.html.slim
h1= @entry.name
= render partial: "document", object: @document


h2 Singleton methods
ul
  - @singleton_methods.each do |meth|
    li= render partial: "entry", object: meth

h2 Instance methods
ul
  - @instance_methods.each do |meth|
    li= render partial: "entry", object: meth

h2 Constants
ul
  - @constants.each do |con|
    li= render partial: "entry", object: con