config/routes.rb
RubyApi::Application.routes.draw do
  root to: "top#index"

  resources :paragraphs, only: [:update]

  lang = /\w\w(-\w\w)?/
  ver = /\d.\d.\d/
  lib = /[a-z].*/

  get ":lang/:version/:library/:module/:::name" => "main#show_constant"       , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module/.:name"  => "main#show_class_method"   , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module/:name"   => "main#show_instance_method", :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module"         => "main#show_module"         , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library"                 => "main#show_library"        , :lang => lang, :version => ver, :library => lib

  get ":lang/:version/:module/:::name" => "main#show_constant"       , :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module/.:name"  => "main#show_class_method"   , :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module/:name"   => "main#show_instance_method", :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module"         => "main#show_module"         , :lang => lang, :version => ver, :library => "_builtin"

  get ":lang/:version" => "main#show_language_top", :lang => lang, :version => ver

  get ":lang" => redirect("/%{lang}/1.9.3"), :lang => lang

end

app/views/view/_show_method.html.slim
h1= @entry.belong_name
- if @document
  pre== @document.text
- else
  div No doc available!

ul
  li= link_to @entry.module.name, @entry.module.path(@language, @version)

app/views/view/show_class.html.slim
h1= @entry.fullname
== @document.body

ul
  - @methods.each do |entry|
    li= link_to entry.fullname, show_method_path(entry, @language)