config/routes.rb
RubyApi::Application.routes.draw do
  root to: "top#index"

  resources :paragraphs, only: [:update]

  lang = /\w\w(-\w\w)?/
  ver = /\d.\d.\d/
  lib = /[a-z].*/

  get ":lang/:version/:library/:module/:::name" => "main#show_constant"       , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module/.:name"  => "main#show_class_method"   , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module/:name"   => "main#show_instance_method", :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library/:module"         => "main#show_module"         , :lang => lang, :version => ver, :library => lib
  get ":lang/:version/:library"                 => "main#show_library"        , :lang => lang, :version => ver, :library => lib

  get ":lang/:version/:module/:::name" => "main#show_constant"       , :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module/.:name"  => "main#show_class_method"   , :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module/:name"   => "main#show_instance_method", :lang => lang, :version => ver, :library => "_builtin"
  get ":lang/:version/:module"         => "main#show_module"         , :lang => lang, :version => ver, :library => "_builtin"

  get ":lang/:version" => "main#show_language_top", :lang => lang, :version => ver

  get ":lang" => redirect("/%{lang}/1.9.3"), :lang => lang

end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title RubyApi
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    = yield :body

app/views/layouts/main.html.slim
- content_for :body do
  #topbar
    #search
      input#search-box type="text"
    #title
      ' Ruby Standard Library API
    #selectors
      = select_tag "version", options_for_select(version_options, current_version)
      = select_tag "language", options_for_select(language_options, current_language)

  #content
    #left
      #left_contents
        h2= t('view.built_in_library')
        #builtin-modules
          ul
            - @modules[0].each do |mod|
              li= render partial: "entry", object: mod
        #builtin_exceptions
          - render_tree(@modules[1]) do |mod|
            = render partial: "entry", object: mod

        h2= t("view.standard_library")
        #standard_libraries
          p (not ready)
          - render_tree(@libraries) do |lm|
            = render partial: "entry", object: lm
        
      ul#search_result

      br

    #right
      #doc
        = yield

= render :template => 'layouts/application'

app/views/layouts/split.html.slim
- content_for :header do
  #search
    input#search-box type="text"
    a href="/"
      | /

- content_for :content do
  #left
    h2 Built-in
    ul
      - @modules.each do |mod|
        li= link_to mod.name, show_module_path(mod)

    h2 Standard library
    ul
      - @libraries.each do |lib|
        li= link_to lib.name, show_library_path(lib)
    br

  #right
    #body
      = yield

= render :template => 'layouts/application'

app/views/layouts/view.html.slim
- content_for :body do
  #header
    #search
      input#search-box type="text"
    #title
      ' Ruby Standard Library API
      = "(#{@language.english_name})"
    #selectors
      = select_tag "version", options_for_select(version_options, current_version)
      = select_tag "language", options_for_select(language_options, current_language)

  #content
    #left
      #left_contents
        h2= t('view.built_in_library')
        #builtin-modules
          ul
            - @modules[0].each do |mod|
              li= render partial: "entry", object: mod
        #builtin_exceptions
          - render_tree(@modules[1]) do |mod|
            = render partial: "entry", object: mod

        h2= t("view.standard_library")
        #standard_libraries
          p (not ready)
          - render_tree(@libraries) do |lm|
            = render partial: "entry", object: lm
        
      ul#search_result

      br

    #right
      #doc
        = yield

= render :template => 'layouts/application'